### ISSUE TITLE
Error during training on Pytorch SageMaker

### ISSUE THREAD

**Issue by dcharrez** [duckietown/aido-on-sagemaker#1]
I got the same error while trying to train with,  6000  max_timesteps, I tried changing other parameters and still get the same error, I also tried changing to GPU but I still don't understand the error.

I works when setting max_timesteps to less than 5000.

RuntimeErrorTraceback (most recent call last)
<ipython-input-5-5193c09c49c9> in <module>()
     13                       hyperparameters=hyperparameters)
     14 
---> 15 estimator.fit('file:///tmp', wait=False)
     16 print("All done!")

/home/ec2-user/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/sagemaker/estimator.pyc in fit(self, inputs, wait, logs, job_name)
    213         self._prepare_for_training(job_name=job_name)
    214 
--> 215         self.latest_training_job = _TrainingJob.start_new(self, inputs)
    216         if wait:
    217             self.latest_training_job.wait(logs=logs)

/home/ec2-user/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/sagemaker/estimator.pyc in start_new(cls, estimator, inputs)
    457                                           resource_config=config['resource_config'], vpc_config=config['vpc_config'],
    458                                           hyperparameters=hyperparameters, stop_condition=config['stop_condition'],
--> 459                                           tags=estimator.tags, metric_definitions=estimator.metric_definitions)
    460 
    461         return cls(estimator.sagemaker_session, estimator._current_job_name)

/home/ec2-user/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/sagemaker/session.pyc in train(self, image, input_mode, input_config, role, job_name, output_config, resource_config, vpc_config, hyperparameters, stop_condition, tags, metric_definitions)
    281         LOGGER.info('Creating training-job with name: {}'.format(job_name))
    282         LOGGER.debug('train request: {}'.format(json.dumps(train_request, indent=4)))
--> 283         self.sagemaker_client.create_training_job(**train_request)
    284 
    285     def tune(self, job_name, strategy, objective_type, objective_metric_name,

/home/ec2-user/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/sagemaker/local/local_session.pyc in create_training_job(self, TrainingJobName, AlgorithmSpecification, OutputDataConfig, ResourceConfig, InputDataConfig, **kwargs)
     72         training_job = _LocalTrainingJob(container)
     73         hyperparameters = kwargs['HyperParameters'] if 'HyperParameters' in kwargs else {}
---> 74         training_job.start(InputDataConfig, OutputDataConfig, hyperparameters, TrainingJobName)
     75 
     76         LocalSagemakerClient._training_jobs[TrainingJobName] = training_job

/home/ec2-user/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/sagemaker/local/entities.pyc in start(self, input_data_config, output_data_config, hyperparameters, job_name)
     68         self.state = self._TRAINING
     69 
---> 70         self.model_artifacts = self.container.train(input_data_config, output_data_config, hyperparameters, job_name)
     71         self.end = datetime.datetime.now()
     72         self.state = self._COMPLETED

/home/ec2-user/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/sagemaker/local/image.pyc in train(self, input_data_config, output_data_config, hyperparameters, job_name)
    128             # which contains the exit code and append the command line to it.
    129             msg = "Failed to run: %s, %s" % (compose_command, str(e))
--> 130             raise RuntimeError(msg)
    131 
    132         artifacts = self.retrieve_artifacts(compose_data, output_data_config, job_name)

RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpDeVteU/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1

![error](https://user-images.githubusercontent.com/8667636/49127674-44e9f680-f296-11e8-8180-f30e34570866.png)

**Comment by bhairavmehta95** [comment]
Can you try removing the `wait=True` from the `estimator.fit()` call? So it should look like:

`estimator.fit('file:///tmp')`

**Comment by dcharrez** [comment]
I still have the same error message, tried on GPU and CPU

```
from sagemaker.estimator import Estimator

hyperparameters = { 'max_timesteps': 6e3 }

estimator = Estimator(role=role,
                      train_instance_count=1,
                      train_instance_type=instance_type,
                      image_name='duckietown_sagemaker:latest',
                      hyperparameters=hyperparameters)

estimator.fit('file:///tmp')
print("All done!")
```

![error_3_pytorch](https://user-images.githubusercontent.com/8667636/49163065-359c9480-f2fa-11e8-8a44-a0b9d1864061.png)

**Comment by bhairavmehta95** [comment]
Ah so I see the issue. It looks like what's happening is that the training step is taking too long, which most likely means you're still trying to train on CPU (have you added `.cuda()` to all the calls to pytorch models?)

An easy way to fix this is to not train for `env_timesteps`, but for a scaled down factor of that (i,e just to make sure your code is working - try using 10 in the `policy.train()` call.)

**Comment by bhairavmehta95** [comment]
I was able to reproduce this and can confirm this was the issue.

To make sure you're grabbing the latest changes, try to pull this repository in sagemaker, and you'll see that there is a line in ddpg.py that was changed to ensure the right device (CPU v GPU was changed).
