### ISSUE TITLE
Empty model after training IL template

### ISSUE THREAD

**Issue by dcharrez** [duckietown/aido-on-sagemaker#2]
No matter what number of epochs i choose, the model is saved on S3 but empty. Tried on CPU and GPU

![error_il](https://user-images.githubusercontent.com/8667636/49175479-aa7dc780-f316-11e8-8505-ea68bb52f030.png)

**Comment by bhairavmehta95** [comment]
Empty in what sense? Like it is an empty file?

**Comment by dcharrez** [comment]
Model.tar.gz is empty, after decompressing

**Comment by bhairavmehta95** [comment]
Okay I think this is an issue with the synchronization between S3 and Sagemaker. I can get back to you in a few hours with a solution.

**Comment by bhairavmehta95** [comment]
So I am testing this now: but the model only saves every 10 epochs by default (if i % 10 == 0)

If you only give it 10 epochs, the loop (due to `for i in range(10)` will product: [0, 1, 2 ... 9].

**Comment by bhairavmehta95** [comment]
So try above, and can you change `STORAGE_LOCATION` to be  `'/opt/ml/model/'` (note the extra slash - apparently  this may also be an issue).

**Comment by dcharrez** [comment]
That `/` was the problem,  Thank you for your time.
